import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const TRUST_CONFIG_FILE = "git-trust.gitconfig";

// Git だけが読む設定ファイルなので、 Revisor 側の同期書き込みで足りる。 同じ内容を
// 何千回も書き直さないよう、 プロセス内で「その path に何を書いたか」を覚える。
const written = new Map();

/** @implements SPEC-MANAGED-GIT-TRUST */
function portable(path) {
  return resolve(path).replaceAll("\\", "/");
}

/** @implements SPEC-MANAGED-GIT-TRUST */
function gitConfigPathValue(path) {
  return `"${portable(path).replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

/**
 * Revisor が git へ global scope として渡す設定ファイルの位置。
 * 解決できない環境 (LOCALAPPDATA も HOME も無い) では null を返し、 呼び出し側は
 * 従来どおり利用者の global 設定のままで動く。
 */
/** @implements SPEC-MANAGED-GIT-TRUST */
export function resolveTrustConfigPath({ env = process.env, platform = process.platform } = {}) {
  if (env.REVISOR_GIT_TRUST_CONFIG) return env.REVISOR_GIT_TRUST_CONFIG;
  if (platform === "win32") {
    return env.LOCALAPPDATA
      ? join(env.LOCALAPPDATA, "LUDIARS", "Revisor", TRUST_CONFIG_FILE)
      : null;
  }
  return env.HOME ? join(env.HOME, ".config", "revisor", TRUST_CONFIG_FILE) : null;
}

/**
 * 取り込む利用者の global 設定。 user.name / credential helper 等は従来どおり効かせる。
 * 既に GIT_CONFIG_GLOBAL が指定されている環境ではそれを尊重する。 ただし自分自身を
 * 指していた場合 (再入した Revisor プロセス) は include の循環になるので無視する。
 */
/** @implements SPEC-MANAGED-GIT-TRUST */
export function resolveUserGlobalConfigPath({
  env = process.env,
  platform = process.platform,
  trustConfigPath = null,
  fileExists = existsSync,
} = {}) {
  const candidate = env.GIT_CONFIG_GLOBAL
    || (platform === "win32"
      ? (env.USERPROFILE ? join(env.USERPROFILE, ".gitconfig") : null)
      : (env.HOME ? join(env.HOME, ".gitconfig") : null));
  if (!candidate || !fileExists(candidate)) return null;
  if (trustConfigPath && portable(candidate) === portable(trustConfigPath)) return null;
  return candidate;
}

/**
 * safe.directory は system / global scope でしか読まれない。 `-c` や GIT_CONFIG_* では
 * local clone の**取得元**リポジトリに届かない (元リポを開くのは子プロセスの
 * `upload-pack` で、 親の command-line scope を引き継がない)。 だから信頼設定は
 * 「Revisor 専用の global 設定ファイル」として渡す。
 *
 * 値が `*` なのは、 LUDIARS の checkout が複数のローカルアカウント (Codex サンドボックス
 * 等) から書かれ、 所有者一致がそもそも成立しないため。 個別 path の列挙は、 新しく
 * 汚染された checkout が出るたびにマージが止まる運用になり、 安定しない。
 */
/** @implements SPEC-MANAGED-GIT-TRUST */
export function buildTrustConfig(userGlobalConfigPath) {
  const lines = [
    "# Generated by Revisor (src/git-trust.mjs). Do not edit by hand.",
  ];
  if (userGlobalConfigPath) {
    lines.push("[include]", `\tpath = ${gitConfigPathValue(userGlobalConfigPath)}`);
  }
  lines.push("[safe]", "\tdirectory = *", "");
  return lines.join("\n");
}

/** @implements SPEC-MANAGED-GIT-TRUST */
export function ensureTrustConfig(path, content, {
  readFile = readFileSync,
  writeFile = writeFileSync,
  makeDirectory = mkdirSync,
} = {}) {
  if (written.get(path) === content) return path;
  let current = null;
  try {
    current = readFile(path, "utf8");
  } catch {
    // 未作成なら作る。 読めない場合も書き直しを試みる。
  }
  if (current !== content) {
    makeDirectory(dirname(path), { recursive: true });
    writeFile(path, content, "utf8");
  }
  written.set(path, content);
  return path;
}

/**
 * git を起動するための環境変数。 信頼設定ファイルを用意して GIT_CONFIG_GLOBAL で指す。
 * 用意できない環境では受け取った env をそのまま返す (機能を落として動かす)。
 */
/** @implements SPEC-MANAGED-GIT-TRUST */
export function gitTrustEnv({
  env = process.env,
  platform = process.platform,
  ensure = ensureTrustConfig,
} = {}) {
  const trustConfigPath = resolveTrustConfigPath({ env, platform });
  if (!trustConfigPath) return env;
  const content = buildTrustConfig(
    resolveUserGlobalConfigPath({ env, platform, trustConfigPath }),
  );
  try {
    ensure(trustConfigPath, content);
  } catch {
    // 設定ファイルを置けないホストでも git 自体は動く。 ここで起動を止めない。
    return env;
  }
  return { ...env, GIT_CONFIG_GLOBAL: trustConfigPath };
}

// テスト用: プロセス内キャッシュを捨てる。
/** @implements SPEC-MANAGED-GIT-TRUST */
export function resetTrustConfigCache() {
  written.clear();
}
