import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const TRUST_CONFIG_FILE = "git-trust.gitconfig";

// Git だけが読む設定ファイルなので、 Revisor 側の同期書き込みで足りる。 同じ内容を
// 何千回も書き直さないよう、 プロセス内で「その path に何を書いたか」を覚える。
const written = new Map();

/** @implements SPEC-MANAGED-GIT-TRUST */
function portable(path) {
  return resolve(path).replaceAll("\\", "/");
}

/** @implements SPEC-MANAGED-GIT-TRUST */
function gitConfigPathValue(path) {
  const value = portable(path);
  if (/[\0-\x1f\x7f]/.test(value)) {
    throw new TypeError("Git trust paths must not contain control characters.");
  }
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

/**
 * Revisor が git へ global scope として渡す設定ファイルの位置。
 * 解決できない環境 (LOCALAPPDATA も HOME も無い) では null を返し、 呼び出し側は
 * 従来どおり利用者の global 設定のままで動く。
 */
/** @implements SPEC-MANAGED-GIT-TRUST */
export function resolveTrustConfigPath({ env = process.env, platform = process.platform } = {}) {
  if (env.REVISOR_GIT_TRUST_CONFIG) return env.REVISOR_GIT_TRUST_CONFIG;
  if (platform === "win32") {
    return env.LOCALAPPDATA
      ? join(env.LOCALAPPDATA, "LUDIARS", "Revisor", TRUST_CONFIG_FILE)
      : null;
  }
  return env.HOME ? join(env.HOME, ".config", "revisor", TRUST_CONFIG_FILE) : null;
}

/**
 * 取り込む利用者の global 設定。 user.name / credential helper 等は従来どおり効かせる。
 * 既に GIT_CONFIG_GLOBAL が指定されている環境ではそれを尊重する。 ただし自分自身を
 * 指していた場合 (再入した Revisor プロセス) は include の循環になるので無視する。
 */
/** @implements SPEC-MANAGED-GIT-TRUST */
export function resolveUserGlobalConfigPath({
  env = process.env,
  platform = process.platform,
  trustConfigPath = null,
  fileExists = existsSync,
} = {}) {
  const candidate = env.GIT_CONFIG_GLOBAL
    || (platform === "win32"
      ? (env.USERPROFILE ? join(env.USERPROFILE, ".gitconfig") : null)
      : (env.HOME ? join(env.HOME, ".gitconfig") : null));
  if (!candidate || !fileExists(candidate)) return null;
  if (trustConfigPath) {
    const portableCandidate = portable(candidate);
    const portableTrustPath = portable(trustConfigPath);
    if (
      portableCandidate === portableTrustPath
      || portableCandidate.startsWith(`${portableTrustPath}.`)
    ) return null;
  }
  return candidate;
}

/**
 * safe.directory は system / global scope でしか読まれない。 `-c` や GIT_CONFIG_* では
 * local clone の**取得元**リポジトリに届かない (元リポを開くのは子プロセスの
 * `upload-pack` で、 親の command-line scope を引き継がない)。 だから信頼設定は
 * 「Revisor 専用の global 設定ファイル」として渡す。
 *
 * 信頼対象は clone / fetch が明示した登録 source に限定する。設定は対象集合ごとに
 * 不変ファイルへ分け、並行する別 repository の呼び出しが内容を書き換えないようにする。
 */
/** @implements SPEC-MANAGED-GIT-TRUST */
export function buildTrustConfig(userGlobalConfigPath, safeDirectories = []) {
  const lines = [
    "# Generated by Revisor (src/git-trust.mjs). Do not edit by hand.",
  ];
  if (userGlobalConfigPath) {
    lines.push("[include]", `\tpath = ${gitConfigPathValue(userGlobalConfigPath)}`);
  }
  lines.push("[safe]");
  for (const directory of [...new Set(safeDirectories.map(portable))].sort()) {
    lines.push(`\tdirectory = ${gitConfigPathValue(directory)}`);
  }
  lines.push("");
  return lines.join("\n");
}

function scopedTrustConfigPath(basePath, content) {
  const digest = createHash("sha256").update(content).digest("hex").slice(0, 16);
  return `${basePath}.${digest}`;
}

/** @implements SPEC-MANAGED-GIT-TRUST */
export function ensureTrustConfig(path, content, {
  readFile = readFileSync,
  writeFile = writeFileSync,
  makeDirectory = mkdirSync,
} = {}) {
  if (written.get(path) === content) return path;
  let current = null;
  try {
    current = readFile(path, "utf8");
  } catch {
    // 未作成なら作る。 読めない場合も書き直しを試みる。
  }
  if (current !== content) {
    makeDirectory(dirname(path), { recursive: true, mode: 0o700 });
    writeFile(path, content, { encoding: "utf8", mode: 0o600 });
  }
  written.set(path, content);
  return path;
}

/**
 * git を起動するための環境変数。 信頼設定ファイルを用意して GIT_CONFIG_GLOBAL で指す。
 * 用意できない環境では受け取った env をそのまま返す (機能を落として動かす)。
 */
/** @implements SPEC-MANAGED-GIT-TRUST */
export function gitTrustEnv({
  env = process.env,
  platform = process.platform,
  safeDirectories = [],
  ensure = ensureTrustConfig,
} = {}) {
  if (safeDirectories.length === 0) return env;
  const baseTrustConfigPath = resolveTrustConfigPath({ env, platform });
  if (!baseTrustConfigPath) return env;
  const content = buildTrustConfig(
    resolveUserGlobalConfigPath({ env, platform, trustConfigPath: baseTrustConfigPath }),
    safeDirectories,
  );
  const trustConfigPath = scopedTrustConfigPath(baseTrustConfigPath, content);
  try {
    ensure(trustConfigPath, content);
  } catch {
    // 設定ファイルを置けないホストでも git 自体は動く。 ここで起動を止めない。
    return env;
  }
  return { ...env, GIT_CONFIG_GLOBAL: trustConfigPath };
}

// テスト用: プロセス内キャッシュを捨てる。
/** @implements SPEC-MANAGED-GIT-TRUST */
export function resetTrustConfigCache() {
  written.clear();
}
